"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.utils.translation import gettext_lazy as _
from django.templatetags.static import static

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)-d4(0q^mzjs#vt40nq1o2+&byq()k)$_)m4s3o279l8$-y3hy'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    'properties',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'




# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "realestate",
        "USER": "realestate",
        "PASSWORD": "realestate",
        "HOST": "db",
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Asia/Tbilisi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


UNFOLD = {
    "SITE_TITLE": _("Панель управления"),
    "SITE_HEADER": _("Недвижимость"),
    "SITE_SYMBOL": "home",  # иконка из Google Material Symbols
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Объявления"),
                "items": [
                    {
                        "title": _("Объекты недвижимости"),
                        "icon": "home",
                        "link": "/admin/properties/property/",
                    },
                ],
            },
            {
                "title": _("Справочники"),
                "items": [
                    {
                        "title": _("Типы сделок"),
                        "icon": "handshake",
                        "link": "/admin/properties/dealtype/",
                    },
                    {
                        "title": _("Типы недвижимости"),
                        "icon": "category",
                        "link": "/admin/properties/propertytype/",
                    },
                    {
                        "title": _("Статусы"),
                        "icon": "label",
                        "link": "/admin/properties/propertystatus/",
                    },
                    {
                        "title": _("Характеристики"),
                        "icon": "tune",
                        "link": "/admin/properties/attribute/",
                    },
                    {
                        "title": _("Варианты выбора"),
                        "icon": "list",
                        "link": "/admin/properties/attributechoice/",
                    },
                    {
                        "title": _("Курс валют"),
                        "icon": "currency_exchange",
                        "link": "/admin/properties/exchangerate/",
                    },
                ],
            },
            {
                "title": _("Система"),
                "items": [
                    {
                        "title": _("Пользователи"),
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": _("Настройки сайта"),
                        "icon": "settings",
                        "link": "/admin/properties/sitesettings/",
                    },
                ],
            },
        ],
    },
}