# Generated by Django 6.0.7 on 2026-07-17 10:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(help_text='Например: rooms, floor, balcony', unique=True, verbose_name='Slug')),
                ('value_type', models.CharField(choices=[('integer', 'Целое число'), ('decimal', 'Десятичное число'), ('boolean', 'Да / Нет'), ('text', 'Текст'), ('choice', 'Вариант выбора')], help_text='Определяет, какое поле будет заполнять администратор.', max_length=10, verbose_name='Тип значения')),
                ('unit', models.CharField(blank=True, help_text='Например: м², эт., км. Отображается рядом со значением.', max_length=20, verbose_name='Единица измерения')),
                ('is_filterable', models.BooleanField(default=True, help_text='Если включено — характеристика доступна в фильтрах на сайте.', verbose_name='Участвует в фильтрации')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='DealType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(help_text='Используется в URL. Только латинские буквы и дефис.', unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Тип сделки',
                'verbose_name_plural': 'Типы сделок',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('usd_to_gel', models.DecimalField(decimal_places=4, help_text='Сколько лари за 1 доллар. Например: 2.6500', max_digits=10, verbose_name='Курс USD → GEL')),
                ('effective_date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Курс валют',
                'verbose_name_plural': 'Курсы валют',
                'ordering': ('-effective_date',),
            },
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(help_text='Например: active, sold, rented, reserved, draft', unique=True, verbose_name='Slug')),
                ('color', models.CharField(blank=True, help_text='Цвет бэйджика на карточке. Например: #27AE60', max_length=7, verbose_name='Цвет (HEX)')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Статус объявления',
                'verbose_name_plural': 'Статусы объявлений',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('whatsapp_number', models.CharField(blank=True, help_text='С кодом страны. Например: +995591234567', max_length=20, verbose_name='Номер WhatsApp')),
                ('phone_number', models.CharField(blank=True, help_text='Отображается на сайте как контактный номер.', max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='properties.attribute', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Вариант выбора',
                'verbose_name_plural': 'Варианты выбора',
                'unique_together': {('attribute', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('city', models.CharField(blank=True, db_index=True, help_text='Например: Тбилиси', max_length=150, verbose_name='Город')),
                ('district', models.CharField(blank=True, db_index=True, help_text='Например: Ваке', max_length=150, verbose_name='Район')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, help_text='Введите цену в выбранной валюте.', max_digits=14, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('GEL', 'GEL')], default='GEL', max_length=3, verbose_name='Валюта')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Кликните на карте, чтобы указать точное местоположение объекта.', null=True, srid=4326, verbose_name='Местоположение на карте')),
                ('address', models.CharField(blank=True, help_text='Заполняется автоматически при клике на карте, можно поправить вручную.', max_length=500, verbose_name='Адрес')),
                ('area_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Общая площадь, м²')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL. Заполняется вручную латиницей.', max_length=255, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(db_index=True, default=True, help_text='Снимите галочку, чтобы скрыть объявление с сайта.', verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_properties', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.dealtype', verbose_name='Тип сделки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertystatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Фотография')),
                ('is_main', models.BooleanField(default=False, help_text='Отображается на превью карточки.', verbose_name='Главное фото')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('alt_text', models.CharField(blank=True, help_text='Для SEO. Например: вид из окна на горы.', max_length=255, verbose_name='Описание фото')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='property_types/', verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('deal_types', models.ManyToManyField(blank=True, help_text='К каким типам сделок относится данная категория.', related_name='property_types', to='properties.dealtype', verbose_name='Применимые типы сделок')),
                ('parent', models.ForeignKey(blank=True, help_text='Оставьте пустым для категории верхнего уровня.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='properties.propertytype', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Тип недвижимости',
                'verbose_name_plural': 'Типы недвижимости',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='properties.propertytype', verbose_name='Тип недвижимости'),
        ),
        migrations.CreateModel(
            name='AttributePropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательна для заполнения')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.attribute', verbose_name='Характеристика')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Связь характеристики с типом',
                'verbose_name_plural': 'Связи характеристик с типами',
            },
        ),
        migrations.AddField(
            model_name='attribute',
            name='property_types',
            field=models.ManyToManyField(related_name='attributes', through='properties.AttributePropertyType', to='properties.propertytype', verbose_name='Типы недвижимости'),
        ),
        migrations.CreateModel(
            name='PropertyTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.propertytype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Перевод типа недвижимости',
                'verbose_name_plural': 'Переводы типов недвижимости',
            },
        ),
        migrations.CreateModel(
            name='AttributeChoiceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.attributechoice', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Перевод варианта выбора',
                'verbose_name_plural': 'Переводы вариантов выбора',
                'unique_together': {('choice', 'language')},
            },
        ),
        migrations.CreateModel(
            name='AttributeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.attribute', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Перевод характеристики',
                'verbose_name_plural': 'Переводы характеристик',
                'unique_together': {('attribute', 'language')},
            },
        ),
        migrations.CreateModel(
            name='DealTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('deal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.dealtype', verbose_name='Тип сделки')),
            ],
            options={
                'verbose_name': 'Перевод типа сделки',
                'verbose_name_plural': 'Переводы типов сделок',
                'unique_together': {('deal_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'unique_together': {('user', 'property')},
            },
        ),
        migrations.CreateModel(
            name='PropertyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('value_integer', models.IntegerField(blank=True, null=True, verbose_name='Значение (целое число)')),
                ('value_decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Значение (дробное число)')),
                ('value_boolean', models.BooleanField(blank=True, null=True, verbose_name='Значение (да/нет)')),
                ('value_text', models.CharField(blank=True, max_length=500, verbose_name='Значение (текст)')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='properties.attribute', verbose_name='Характеристика')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='properties.property', verbose_name='Объект')),
                ('value_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.attributechoice', verbose_name='Значение (вариант)')),
            ],
            options={
                'verbose_name': 'Значение характеристики',
                'verbose_name_plural': 'Значения характеристик',
                'indexes': [models.Index(fields=['attribute', 'value_integer'], name='properties__attribu_89de02_idx'), models.Index(fields=['attribute', 'value_decimal'], name='properties__attribu_fd606d_idx'), models.Index(fields=['attribute', 'value_boolean'], name='properties__attribu_29cd3d_idx'), models.Index(fields=['attribute', 'value_choice'], name='properties__attribu_1cab44_idx')],
                'unique_together': {('property', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='PropertyStatusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.propertystatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Перевод статуса',
                'verbose_name_plural': 'Переводы статусов',
                'unique_together': {('status', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'English'), ('ka', 'ქართული')], db_index=True, max_length=2, verbose_name='Язык')),
                ('title', models.CharField(help_text='Например: 3-комнатная квартира в центре Тбилиси', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address_text', models.CharField(blank=True, help_text='Например: ул. Руставели 5, кв. 12. Отображается на карточке.', max_length=500, verbose_name='Адрес (текст)')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='properties.property', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Перевод объекта',
                'verbose_name_plural': 'Переводы объектов',
                'unique_together': {('property', 'language')},
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['deal_type', 'property_type', 'status'], name='properties__deal_ty_8ba68a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributepropertytype',
            unique_together={('attribute', 'property_type')},
        ),
        migrations.AlterUniqueTogether(
            name='propertytypetranslation',
            unique_together={('property_type', 'language')},
        ),
    ]
