# Generated by Django 6.0.6 on 2026-07-01 13:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, help_text='Заполняется автоматически при клике на карте, можно поправить вручную.', max_length=500, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Кликните на карте, чтобы указать точное местоположение объекта.', null=True, srid=4326, verbose_name='Местоположение на карте'),
        ),
    ]
