# Generated by Django 6.0.7 on 2026-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_living',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для домов — площадь самого строения.', max_digits=10, null=True, verbose_name='Площадь дома / жилая площадь, м²'),
        ),
        migrations.AlterField(
            model_name='property',
            name='area_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Для домов — площадь земельного участка. Для квартир — общая площадь.', max_digits=10, null=True, verbose_name='Площадь участка / общая площадь, м²'),
        ),
    ]
